# Generated by Django 5.0.14 on 2026-07-18 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('inventory', 'Inventory Staff'), ('people', 'People Staff'), ('transactions', 'Transactions Staff'), ('reports', 'Reports Staff')], default='admin', max_length=20),
        ),
    ]
