# Generated by Django 5.0.14 on 2026-07-18 00:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('brands', '0001_initial'),
        ('categories', '0001_initial'),
        ('suppliers', '0001_initial'),
        ('units', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(db_index=True, max_length=50, unique=True)),
                ('barcode', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('purchase_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('selling_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('tax', models.DecimalField(decimal_places=2, default=0, help_text='Tax percentage', max_digits=5)),
                ('current_stock', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('minimum_stock', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('maximum_stock', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='brands.brand')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='categories.category')),
                ('supplier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='suppliers.supplier')),
                ('unit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='units.unit')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['name', 'status'], name='products_pr_name_73da9f_idx'), models.Index(fields=['sku', 'barcode'], name='products_pr_sku_13ed68_idx')],
            },
        ),
    ]
